# Generated by Django 4.2.2 on 2023-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='token',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
