# Generated by Django 4.2.2 on 2023-07-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user_input',
            new_name='profile',
        ),
    ]
