# Generated by Django 4.2.2 on 2023-07-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_user_input_agent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
